# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm_cens <- function(X, mu, Sigma, missingness_labels_i, nonmissing_features, logd = FALSE, lambda = 0) {
    .Call(`_communication_dmvnorm_cens`, X, mu, Sigma, missingness_labels_i, nonmissing_features, logd, lambda)
}

dmvnorm_cond <- function(X, mu, Sigma, labels_t, labels_y, logd = FALSE, lambda = 0) {
    .Call(`_communication_dmvnorm_cond`, X, mu, Sigma, labels_t, labels_y, logd, lambda)
}

forward <- function(delta, Gamma, tstateprobs, scale) {
    .Call(`_communication_forward`, delta, Gamma, tstateprobs, scale)
}

backward <- function(Gamma, tstateprobs, scale) {
    .Call(`_communication_backward`, Gamma, tstateprobs, scale)
}

hmm_cpp <- function(Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, nonmissing, missingness_labels, nonmissing_features, lambda = 0, tol = 1e-6, maxiter = 100L, uncollapse = 0, verbose = TRUE, supervised = FALSE) {
    .Call(`_communication_hmm_cpp`, Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, nonmissing, missingness_labels, nonmissing_features, lambda, tol, maxiter, uncollapse, verbose, supervised)
}

hmm_autocorr_cpp <- function(Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, labels_t, labels_y, lambda = 0, tol = 1e-6, maxiter = 100L, uncollapse = 0, verbose = TRUE, supervised = FALSE) {
    .Call(`_communication_hmm_autocorr_cpp`, Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, labels_t, labels_y, lambda, tol, maxiter, uncollapse, verbose, supervised)
}

llh_cpp <- function(Xs, delta, mus, Sigmas_in, Gamma, nonmissing, missingness_labels, nonmissing_features, lambda, verbose = TRUE) {
    .Call(`_communication_llh_cpp`, Xs, delta, mus, Sigmas_in, Gamma, nonmissing, missingness_labels, nonmissing_features, lambda, verbose)
}

lstateprobs_cpp <- function(Xs, mus, Sigmas_in, nonmissing, missingness_labels, nonmissing_features, lambda) {
    .Call(`_communication_lstateprobs_cpp`, Xs, mus, Sigmas_in, nonmissing, missingness_labels, nonmissing_features, lambda)
}

viterbi_cpp <- function(lstateprobs, delta, Gamma) {
    .Call(`_communication_viterbi_cpp`, lstateprobs, delta, Gamma)
}

rcpp_parseAudioFile <- function(strWavfile) {
    .Call(`_communication_rcpp_parseAudioFile`, strWavfile)
}

rcpp_playWavFile <- function(header, rawData) {
    .Call(`_communication_rcpp_playWavFile`, header, rawData)
}

test_rcpp_playWavFile <- function(strWavfile) {
    .Call(`_communication_test_rcpp_playWavFile`, strWavfile)
}

rcpp_writeAudioFile <- function(header, rawData, filePath) {
    invisible(.Call(`_communication_rcpp_writeAudioFile`, header, rawData, filePath))
}

rcpp_writeAudioFileStereo <- function(header, rawDataL, rawDataR, filePath) {
    invisible(.Call(`_communication_rcpp_writeAudioFileStereo`, header, rawDataL, rawDataR, filePath))
}

test_rcpp_writeWavFile <- function(filePathIn, filePathOut) {
    invisible(.Call(`_communication_test_rcpp_writeWavFile`, filePathIn, filePathOut))
}

rcpp_openSmileGetFeatures <- function(audio_files_in, config_string_in) {
    .Call(`_communication_rcpp_openSmileGetFeatures`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetFeatures <- function(audio_files_in, config_file_in) {
    .Call(`_communication_test_rcpp_openSmileGetFeatures`, audio_files_in, config_file_in)
}

rcpp_openSmileGetBorderFrames <- function(audio_files_in, config_string_in) {
    .Call(`_communication_rcpp_openSmileGetBorderFrames`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetBorderFrames <- function(audio_files_in, config_file_in) {
    .Call(`_communication_test_rcpp_openSmileGetBorderFrames`, audio_files_in, config_file_in)
}

rcpp_openSmileMain <- function(arguments) {
    .Call(`_communication_rcpp_openSmileMain`, arguments)
}

rcpp_openSmileGetFeatures_Turns <- function(audio_files_in, config_string_in) {
    .Call(`_communication_rcpp_openSmileGetFeatures_Turns`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetFeatures_Turns <- function(audio_files_in, config_file_in) {
    .Call(`_communication_test_rcpp_openSmileGetFeatures_Turns`, audio_files_in, config_file_in)
}

