# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm_cens <- function(X, mu, Sigma, missingness_labels_i, nonmissing_features, logd = FALSE, lambda = 0) {
    .Call(`_speech_dmvnorm_cens`, X, mu, Sigma, missingness_labels_i, nonmissing_features, logd, lambda)
}

dmvnorm_cond <- function(X, mu, Sigma, labels_t, labels_y, logd = FALSE, lambda = 0) {
    .Call(`_speech_dmvnorm_cond`, X, mu, Sigma, labels_t, labels_y, logd, lambda)
}

forward <- function(delta, Gamma, tstateprobs, scale) {
    .Call(`_speech_forward`, delta, Gamma, tstateprobs, scale)
}

backward <- function(Gamma, tstateprobs, scale) {
    .Call(`_speech_backward`, Gamma, tstateprobs, scale)
}

hmm_cpp <- function(Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, nonmissing, missingness_labels, nonmissing_features, lambda = 0, tol = 1e-6, maxiter = 100L, uncollapse = 0, verbose = TRUE, supervised = FALSE) {
    .Call(`_speech_hmm_cpp`, Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, nonmissing, missingness_labels, nonmissing_features, lambda, tol, maxiter, uncollapse, verbose, supervised)
}

hmm_autocorr_cpp <- function(Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, labels_t, labels_y, lambda = 0, tol = 1e-6, maxiter = 100L, uncollapse = 0, verbose = TRUE, supervised = FALSE) {
    .Call(`_speech_hmm_autocorr_cpp`, Xs, weights, delta_init, mus_init, Sigmas_init, Gamma_init, zetas_init, labels_t, labels_y, lambda, tol, maxiter, uncollapse, verbose, supervised)
}

llh_cpp <- function(Xs, delta, mus, Sigmas_in, Gamma, nonmissing, missingness_labels, nonmissing_features, lambda, verbose = TRUE) {
    .Call(`_speech_llh_cpp`, Xs, delta, mus, Sigmas_in, Gamma, nonmissing, missingness_labels, nonmissing_features, lambda, verbose)
}

lstateprobs_cpp <- function(Xs, mus, Sigmas_in, nonmissing, missingness_labels, nonmissing_features, lambda) {
    .Call(`_speech_lstateprobs_cpp`, Xs, mus, Sigmas_in, nonmissing, missingness_labels, nonmissing_features, lambda)
}

viterbi_cpp <- function(lstateprobs, delta, Gamma) {
    .Call(`_speech_viterbi_cpp`, lstateprobs, delta, Gamma)
}

wavToMp3 <- function(wav_file_in, mp3_file_out) {
    invisible(.Call(`_speech_wavToMp3`, wav_file_in, mp3_file_out))
}

mp3ToWav <- function(mp3_file_in, wav_file_out) {
    invisible(.Call(`_speech_mp3ToWav`, mp3_file_in, wav_file_out))
}

rcpp_parseWavFile <- function(strWavfile) {
    .Call(`_speech_rcpp_parseWavFile`, strWavfile)
}

rcpp_playWavFile <- function(rawData, header) {
    .Call(`_speech_rcpp_playWavFile`, rawData, header)
}

test_rcpp_playWavFile <- function(strWavfile) {
    .Call(`_speech_test_rcpp_playWavFile`, strWavfile)
}

rcpp_writeWavFile <- function(filePath, rawData, header) {
    invisible(.Call(`_speech_rcpp_writeWavFile`, filePath, rawData, header))
}

test_rcpp_writeWavFile <- function(filePathIn, filePathOut) {
    invisible(.Call(`_speech_test_rcpp_writeWavFile`, filePathIn, filePathOut))
}

rcpp_openSmileGetFeatures <- function(audio_files_in, config_string_in) {
    .Call(`_speech_rcpp_openSmileGetFeatures`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetFeatures <- function(audio_files_in, config_file_in) {
    .Call(`_speech_test_rcpp_openSmileGetFeatures`, audio_files_in, config_file_in)
}

rcpp_openSmileGetBorderFrames <- function(audio_files_in, config_string_in) {
    .Call(`_speech_rcpp_openSmileGetBorderFrames`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetBorderFrames <- function(audio_files_in, config_file_in) {
    .Call(`_speech_test_rcpp_openSmileGetBorderFrames`, audio_files_in, config_file_in)
}

rcpp_openSmileMain <- function(arguments) {
    .Call(`_speech_rcpp_openSmileMain`, arguments)
}

rcpp_openSmileGetFeatures_Turns <- function(audio_files_in, config_string_in) {
    .Call(`_speech_rcpp_openSmileGetFeatures_Turns`, audio_files_in, config_string_in)
}

test_rcpp_openSmileGetFeatures_Turns <- function(audio_files_in, config_file_in) {
    .Call(`_speech_test_rcpp_openSmileGetFeatures_Turns`, audio_files_in, config_file_in)
}

